services:
  - type: web
    name: data-cleaner
    env: python
    pythonVersion: "3.11"
    repo: "https://github.com/traore8issiaka1/data_cleaner-MDSI.git"
    branch: main
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
