# Render service configuration — repo mis à jour
services:
  - type: web
    name: data-cleaner
    env: python
    pythonVersion: "3.11"
    repo: "https://github.com/traore8issiaka1/data_cleaner-MDSI.git"
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
